# Generated by Django 2.2.24 on 2021-08-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dwolla_customer_id',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dwolla_funding_source_id',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
