# Generated by Django 2.2.24 on 2021-09-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210823_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dwolla_funding_source_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='dwolla_balance_funding_source_id',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dwolla_customer_url',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dwolla_customer_id',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
