# Generated by Django 2.2.24 on 2021-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210912_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tilled_customer_id',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
