# Generated by Django 2.2.24 on 2021-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_tilled_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onesignal_user_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
