export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const CLEAR_SIGNUP_ERROR = 'CLEAR_SIGNUP_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const GET_LOGGED_USER = 'GET_LOGGED_USER';
export const GET_LOGGED_USER_SUCCESS = 'GET_LOGGED_USER_SUCCESS';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';

export const FACEBOOK_SIGNUP = 'FACEBOOK_SIGNUP';
export const FACEBOOK_SIGNUP_SUCCESS = 'FACEBOOK_SIGNUP_SUCCESS';
export const FACEBOOK_SIGNUP_ERROR = 'FACEBOOK_SIGNUP_ERROR';

export const GOOGLE_SIGNUP = 'GOOGLE_SIGNUP';
export const GOOGLE_SIGNUP_SUCCESS = 'GOOGLE_SIGNUP_SUCCESS';
export const GOOGLE_SIGNUP_ERROR = 'GOOGLE_SIGNUP_ERROR';

export const APPLE_ID_SIGNUP = 'APPLE_ID_SIGNUP';
export const APPLE_ID_SIGNUP_SUCCESS = 'APPLE_ID_SIGNUP_SUCCESS';
export const APPLE_ID_SIGNUP_ERROR = 'APPLE_ID_SIGNUP_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const TOKEN_KEY = '@token';
export const USER_VERIFIED = '@verified';
export const TERMS_AGREED = '@terms';
export const USERNAME = '@username';
export const EMAIL = '@email';
export const HAS_USERNAME = '@hasUsername';
export const APPLE_ID_EMAIL = '@appleidemail';
export const USER_ID = '@userId';
export const ONE_SIGNAL_USER_ID = '@onesignalUserId';

export const VERIFY_CODE = 'VERIFY_CODE';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_ERROR = 'VERIFY_CODE_ERROR';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const RESET_CODE = 'RESET_CODE';
export const RESET_CODE_SUCCESS = 'RESET_CODE_SUCCESS';
export const RESET_CODE_ERROR = 'RESET_CODE_ERROR';

export const USERNAME_EXIST = 'USERNAME_EXIST';
export const USERNAME_EXIST_SUCCESS = 'USERNAME_EXIST_SUCCESS';
export const USERNAME_EXIST_ERROR = 'USERNAME_EXIST_ERROR';

export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_USERNAME_SUCCESS = 'UPDATE_USERNAME_SUCCESS';
export const UPDATE_USERNAME_ERROR = 'UPDATE_USERNAME_ERROR';

export const UPDATE_USER_ACCOUNT = 'UPDATE_USER_ACCOUNT';
export const UPDATE_USER_ACCOUNT_SUCCESS = 'UPDATE_USER_ACCOUNT_SUCCESS';
