# Generated by Django 2.2.20 on 2021-05-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0, help_text='Account balance', verbose_name='Account balance')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='user_profile.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
