# Generated by Django 2.2.24 on 2021-10-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('dwolla', 'Dwolla'), ('yenne', 'Yenne'), ('tilled', 'Tilled')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(choices=[('dwolla', 'Dwolla'), ('yenne', 'Yenne'), ('tilled', 'Tilled')], default='dwolla', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='user_profile.Profile'),
        ),
    ]
