# Generated by Django 2.2.20 on 2021-05-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=35, unique=True)),
                ('holder', models.CharField(max_length=150)),
                ('cvv', models.CharField(max_length=5)),
                ('expiry', models.CharField(max_length=7)),
                ('is_primary', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='user_profile.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
