# Generated by Django 2.2.24 on 2021-08-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcard',
            options={'ordering': ('-is_primary',)},
        ),
    ]
