# Generated by Django 2.2.24 on 2021-09-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210823_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='tilled_payment_method_id',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
