# Generated by Django 2.2.20 on 2021-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_username',
            field=models.SmallIntegerField(default=0),
        ),
    ]
