# Generated by Django 2.2.20 on 2021-04-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_has_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='apple_nonce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
