export const LIST_FUNDING_SOURCE = 'LIST_FUNDING_SOURCE';
export const LIST_FUNDING_SOURCE_SUCCESS = 'LIST_FUNDING_SOURCE_SUCCESS';
export const LIST_FUNDING_SOURCE_FAIL = 'LIST_FUNDING_SOURCE_FAIL';

export const DELETE_FUNDING_SOURCE = 'DELETE_FUNDING_SOURCE';
export const DELETE_FUNDING_SOURCE_SUCCESS = 'DELETE_FUNDING_SOURCE_SUCCESS';
export const DELETE_FUNDING_SOURCE_FAIL = 'DELETE_FUNDING_SOURCE_FAIL';

export const GET_BALANCE = 'GET_BALANCE';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAIL = 'GET_BALANCE_FAIL';

export const TRANSFER_TO_BALANCE = 'TRANSFER_TO_BALANCE';
export const TRANSFER_TO_BALANCE_SUCCESS = 'TRANSFER_TO_BALANCE_SUCCESS';
export const TRANSFER_TO_BALANCE_FAIL = 'TRANSFER_TO_BALANCE_FAIL';

export const DEPOSIT = 'DEPOSIT';
export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS';
export const DEPOSIT_FAIL = 'DEPOSIT_FAIL';

export const SEND_MONEY = 'SEND_MONEY';
export const SEND_MONEY_SUCCESS = 'SEND_MONEY_SUCCESS';
export const SEND_MONEY_FAIL = 'SEND_MONEY';
